[build]
  command = "npm run build"
  publish = "dist"

# Disable secret detection for client-side environment variables
# Client-side apps MUST expose API keys in the browser
[build.environment]
  NETLIFY_SKIP_SECRET_DETECTION = "true"
