[build]
  command = "npm run build"
  publish = "dist"

# Build configuration
[build.environment]
  NODE_VERSION = "18"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
